### ISSUE TITLE
REQUEST: Allow comments in user CSS

### ISSUE THREAD

**Issue by Kreyren** [hohMiyazawa/Automail#23]
Using this css https://github.com/Kreyren/anilist_css/blob/master/core.css with automail does not work, because automail does not work with comments.

### Expected behavior

Expecting automail to work with comments.

### Minimal example:

With comment:
```css
/* Font color */
.time[data-v-6994d971],
.stat .label[data-v-815ccddc],
.nav .link[data-v-66e5278e],
.el-dropdown-menu,
el-dropdown-menu__item, body, h1, h2, h3, p {
	color: rgb(255, 219, 0);
}
```

Without comment:
```css
.time[data-v-6994d971],
.stat .label[data-v-815ccddc],
.nav .link[data-v-66e5278e],
.el-dropdown-menu,
el-dropdown-menu__item, body, h1, h2, h3, p {
	color: rgb(255, 219, 0);
}
```
